### ISSUE TITLE
Help please

### ISSUE THREAD

**Issue by roryleitch** [jamhamster/AlyxCheats#1]
What buttons do i press

**Comment by jamhamster** [comment]
You need a joystick or gamepad plugged in, once you do, use these buttons to activate the options. 

JOY1 Spawns a Grenade (only use on later levels or an ERROR is spawned)

JOY2 Look in a direction and press a button and this will create a sound object that Jeff will follow, only use this on the Jeff level as an error is produced on any other level.

JOY3 Notarget – Makes you invisible to most enemies (Except Jeff, he’s a scamp!)

JOY4 Gives all weapons

JOY5 Upgrades all weapons to max.

**Comment by roryleitch** [comment]
is there no way to bind these to a vr controller

**Comment by roryleitch** [comment]
also is this the dpad for the abxy buttons

**Comment by jamhamster** [comment]
It would be the joystick buttons (they're Joy 1, 2,, etc.) 

To bind the same actions to keys, type this in the console:

bind c "give item_hlvr_grenade_frag"
bind v "hl_blind_zombie_generate_sound"
bind b "give item_hlvr_prop_battery"
bind n "Impulse 101"
bind m "Impulse 102"

**Comment by roryleitch** [comment]
what conntroller is this for?

**Comment by jamhamster** [comment]
The keyboard. There is no way to bind this to a VR controller. :-)

**Comment by roryleitch** [comment]
no the normal bindings

**Comment by roryleitch** [comment]
also would it work with Nintendo joycons

**Comment by jamhamster** [comment]
Okay, I think I've figured out what you're after.

The standard bindings for the mod are linked to a standard windows joystick assignment where joystick button 1 would be JOY 1, Joystick button 2 would be JOY 2 etc. 

Any joystick/gamepad would register in this way and shoudl work with the mod. 

You have two choices:

1: Get a standard USB gamepad joystick and plug it in
2: Use the keyboard bindings above

It is probably possible to get the JoyCon controllers to work but you would need to pair them to your PC with bluetooth first and do a lot of messing around, it is likely too much hassle.
